version: "3.7"

services:
  pcit:
    # restart: always
    image: khs1994/pcit:alpine
    volumes:
      - pcit/key:/app/pcit/public/storage/private_key:cached
      - pcit/.env.${APP_ENV:-development}:/app/pcit/public/.env.${APP_ENV:-development}:cached
      - ./config/php/${LNMP_PHP_INI:-php.development.ini}:/usr/local/etc/php/php.ini:ro
      - pcit-tmp:/tmp
      - zoneinfo-data:/usr/share/zoneinfo
      - composer_cache-data:/tmp/cache
    networks:
      - backend
    working_dir: /app/pcit/bin
    command:
      - /bin/sh
      - pcitd
      - up
    environment:
      - APP_ENV=${APP_ENV:-development}

  nginx:
    ports:
      - "${LNMP_NGINX_HTTPS_PORT:-0.0.0.0:443}:443"
      - "${LNMP_NGINX_HTTP_PORT:-0.0.0.0:80}:80"
      - "${LNMP_PCIT_PORT:-0.0.0.0:10000}:10000"

volumes:
  pcit-tmp:
